### ISSUE TITLE
Module settings not available

### ISSUE THREAD

**Issue by Woodchip50** [eXaminator/kanka-foundry#70] opened 2021-08-07 13:34 UTC
Hi, 

Not sure exactly what's going on here. I have used this amazing module for a while now - it all worked great, and was one of my favourite modules! But at some point in the last month or so the module has stopped functioning...

So - I have both it and its dependency (lib doc-) listed as active modules on module management. But when I go to configure settings - module settings, neither are showing up on my list. I also don't have the kanka button on my journal entry tab. It's just not appearing anywhere.

I have disabled and re-enabled the module, same with lib document sheet registrar. I'm on foundry v.0.8.8, D&D 5e v.1.4.1. Removed all my outdated modules (re-enabled when that didn't help).
Not sure what else to try? Any ideas would be greatly appreciated! 

Thanks!

**Comment by eXaminator** [comment] 2021-08-07 13:57
Hey, that sounds very strange.

It sounds like you are running into some kind of error. So I would like you to have a look in your browser console and see if there are any errors shown.

In case you don't know how to do that: Open your console (F12 on Windows / Option + ⌘ + J on Mac OS)  and ensure that you are on the "console" tab. Now reload your foundry in your browser while you are inside your world. You'll see a lot of different messages. What you'll be looking for are error messages that will be highlighted in red.

If you could post either a screenshot or copy/paste the error (or multiple errors) you see, that would be helpful!

If you are using the local installation of Foundry, with which I'm not all too familiar, you might be able to open the console there too. If not, maybe you can connect via your browser instead (like players would) and join as the GM via that and perform the above mentioned steps.

**Comment by Nyx-na** [comment] 2021-08-07 23:19
I'm also having this problem, I don't know if this is the print you asked for, but if it helps to solve it.
https://imgur.com/aBJ4Z9k

**Comment by eXaminator** [comment] 2021-08-08 07:45
Hi @Nyx-na,

thanks, that helps. Though I'd also like to see if @Woodchip50 has the same error.

But in your case, I'd just like to confirm that you have
1. installed the latest version of Kanka-Foundry
2. installed the latest version of "Lib: Document Sheet Registrar"
3. activated "Lib: Document Sheet Registrar" in your world

Thanks for your help in hopefully pinning this error down!

**Comment by DavidAremaCarretero** [comment] 2021-08-08 13:44
Same here, with latest versions for Kanka and dependency.
![image](https://user-images.githubusercontent.com/1208628/128634039-b627fa69-18cc-4993-88f6-35e3353ce120.png)

**Comment by Woodchip50** [comment] 2021-08-08 14:58
Thanks @eXaminator for the quick reply! 

Attached are the console entries related to kanka. Hope they're enlightening! Mean absolutely nothing to me! 

![kanka issue image](https://user-images.githubusercontent.com/70519637/128636293-4969ae01-010d-4b19-81d5-7c744c343503.png)

**Comment by eXaminator** [comment] 2021-08-08 15:12
Thanks for all your input. I have an idea what the problem could be.

It would be awesome if all of you could give me the following information:
- What version of Foundry are you running?
- How are you running foundry (local application, node application, hosted etc.)?
- What operating system is your foundry instance running on (Windows, Mac, Linux)?
- If not using the local application: What Browser are you using to access foundry?

Thank you all for your help!

For anyone interested: We already noticed that the sheet registration library seems to be loaded by foundry **after** Kanka-Foundry is loaded. Though we weren't able to reproduce this reliably. I can't be sure, but I think this might be your problems too. I hope your information  can help us to pinpoint the origin of this problem and possibly find a way to fix this.

**Comment by eXaminator** [comment] 2021-08-08 20:12
Ok, so I just pushed a change that **should** fix this issue. But because I'm not 100% sure I'll keep this issue open for a little while to see if it worked.

I'm still interested in answers to the above questions from people who had the problem.

Also, please let me know if the issue is fixed for you with the latest release or if any new issues pop up.

**Comment by newnoisethriller** [comment] 2021-08-08 20:33
Hi, I'm also having this issue. 

-Using Foundry Version 0.8.8.
-Pathfinder 2nd Edition Version 2.11.1.7257
-Locally hosting
-Running Windows 11 Version 10.0.22000.

Just updated to Kanka Vserion 2.3.9 and it looks like it's all running normally again! Thanks!

**Comment by Nyx-na** [comment] 2021-08-08 20:40
Thanks @eXaminator, solved the issue for me with the update.

Foundry version 0.8.8, local application, Windows 10.

The module is really great and helps me a lot to manage my foundry campaigns!!!

**Comment by DavidAremaCarretero** [comment] 2021-08-08 22:43
Working for me also on new version :) thanks a lot! 👍

**Comment by Woodchip50** [comment] 2021-08-09 08:08
Just updated and it seem to be working again! Thank you! 

In case it's useful for the future - I am also locally hosting, Windows 10, Foundry v0.8.8

**Comment by eXaminator** [comment] 2021-08-12 20:10
I'll close this as it seems to be fixed for now.

**Closed by eXaminator** 2021-08-12 20:10 UTC
