### ISSUE TITLE
Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by LeeDurant** [eXaminator/kanka-foundry#126] opened 2023-11-28 01:30 UTC
Following errors are given when trying to link items either individually or by clicking "link all" button. 

Journal entries from previous syncs have been deleted, issue remains.

![Untitled](https://github.com/eXaminator/kanka-foundry/assets/50924770/eda24c3d-5cb9-4d96-9903-7b8a7ba39e0f)

module updated 11/27/2023

**Comment by eXaminator** [comment] 2023-12-03 17:48
Sadly I cannot reproduce this error.

Can you please check your browsers console (F12 on Windows) for any errors related to Kanka and post a screenshot of that here?

**Comment by LeeDurant** [comment] 2023-12-04 21:41
![image](https://github.com/eXaminator/kanka-foundry/assets/50924770/59f108fc-29bb-4f0a-813a-53e400c73efd)

**Comment by eXaminator** [comment] 2023-12-04 21:47
Thanks. I'm wondering if this has something to do with another module. Could you disable all modules besides kanka and check if it's still broken? If not, please enable module by module and see which one breaks it. If you can find out which module I'd the culprit I might be able to check whether I can fix it somehow or if we'd need to open an issue with that other module.

**Comment by LeeDurant** [comment] 2023-12-05 01:44
![image](https://github.com/eXaminator/kanka-foundry/assets/50924770/04262029-4082-478c-b8c2-30b770a1f495)

Still getting this after deactivating all modules. I am running the [Avatar Legends](https://foundryvtt.com/packages/legends) system on Foundry v.11.315

**Comment by eXaminator** [comment] 2023-12-05 07:49
I will test with the system, but looking at that error it might be something else too. Does that happen with all syncs? Or just one specific entity? Do you have any special characters in the names or anywhere else in these entities?

**Comment by LeeDurant** [comment] 2023-12-05 14:27
No special characters. It's extremely irregular, no real pattern I can identify. Some are characters, others are locations. 

The Kanka pages use standard formatting with no special HTML insertions other than those built in for linking to other pages.

**Comment by LeeDurant** [comment] 2023-12-12 15:33
Here's what I got after trying to link a single entry:

![image](https://github.com/eXaminator/kanka-foundry/assets/50924770/227aaa8c-e3e7-48ed-b2c2-5627a0e93d65)

**Comment by eXaminator** [comment] 2023-12-12 15:49
Hey, thanks! But that's basically what you sent before. When in the devtools, at the top of the devtools panel you should have a tab called "network" that looks a bit like this:

![image](https://github.com/eXaminator/kanka-foundry/assets/2758908/31f0a459-aeb9-4230-bbc6-4b4917ff8a22)

In there you should see all network requests made by your browser. If you now sync an entity you should see new requests starting to appear in that list (probably at the bottom). If you click on those requests you should get some more details, including another tab called "Response". That should contain the data of the entry you just tried to sync in a more technical format. That's the info I was asking about previously, as it hopefully shows me what is "wrong" with the entity in a way that hopefully allows me to fix the issue on my end :)

**Comment by LeeDurant** [comment] 2023-12-20 15:56
Could it be an issue with the uploaded image? .webp vs .png vs .jpeg?

**Comment by eXaminator** [comment] 2023-12-20 18:27
Thanks for all the info! I'm sure this will help me find out what the problem is. My guess right now is, that your entry has some characters in it that foundry has problems parsing. But I will see if I can get some more specific info on this in the next few days or so and will come back to you once I know anything. If my guess is right though, than I'm not sure if it's something that I can easily fix, or whether it's something that should be fixed in either the Foundry core or Kanka itself. But I should know more in a few days.

**Comment by eXaminator** [comment] 2023-12-20 21:02
Hi @LeeDurant , I just took a quick look into it and am seeing some strange behavior of which I'm not sure where it comes from.

To make sure I can replicate the issue as best as possible I have to ask one more favor of you: Could you go into the above mentioned entry in Kanka, edit it and then click the source code icon (see below) and provide the whole content of that entry "as is" for me? I tried extracting that from your previous response dump, but I'm seeing differences in what Kanka sends me when I do that. So I'm hoping to be able to replicate the problem by getting the actual content of your entry. Thanks!

<img width="41" alt="image" src="https://github.com/eXaminator/kanka-foundry/assets/2758908/8a594b66-fe03-4d0a-93c7-8d6c81867ec3">

**Comment by LeeDurant** [comment] 2023-12-21 01:17
'<p dir="ltr"><span style="font-size:26pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Hajime-Taiyo Chiu-Wei, The Elder</span></p><p dir="ltr"><span style="font-size:15pt;font-family:Arial, sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">I don’t want to hurt people anymore</span></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Age: 45</span></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Careers: Ex-Military, “Old dad” just trying to get it together</span></p><p><b><br></b></p><h3><span style="font-size:13.999999999999998pt;font-family:Arial, sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">“See the world, go to exotic places, Join the Army, and travel around the world for nothing.”&nbsp;</span></h3><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Hajime-Taiyo wasn’t sure what he wanted to do with his life being secondborn meant his life wasn’t as pre-determined as his older brother's. But raising a village out of the earth and the labor associated with it wasn’t how he planned to make his mark on the world. Village be damned, he would make his way with or without his family. Oh to be young and dumb again.&nbsp;</span></p><h3><span style="font-size:13.999999999999998pt;font-family:Arial, sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">“Never forget”</span></h3><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">While in basic training, Republic City was attacked by the “Great unifier” General Kuvira. He will always remember the furver he felt in that moment. Months of&nbsp; aptitude testing, drilling, medical evaluations, combat exercises, medical and psychological testing. Learning the ins and outs of other martial arts and bending forms as well as the histories of the other nations. All while learning about machines that wouldn’t be common place in the village he grew up in for years.</span><span style="border:none;width:210px;height:210px;"><img src="https://lh7-us.googleusercontent.com/RoYJRL5r7CX3Xj1DlHM5Dyc74_5elcFeHaO5gx_OmVQTlaRmfPjVrUCJyfCeo0ZmGl6jbY99dT20EhSrUgEPn8c5WhuWq4iE7QxXzRaMYby8ZObIOxr6J8jb8M9mioOEhMYJj8sc9aHsQV4J8mowMjY" width="210" height="210" style="margin-left:0px;" alt="RoYJRL5r7CX3Xj1DlHM5Dyc74_5elcFeHaO5gx_OmVQTlaRmfPjVrUCJyfCeo0ZmGl6jbY99dT20EhSrUgEPn8c5WhuWq4iE7QxXzRaMYby8ZObIOxr6J8jb8M9mioOEhMYJj8sc9aHsQV4J8mowMjY"></span></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">And at last he would be able to put all these things to work and not just on bandits or some provincial Warlord. But real soliders trained for war. He would make his mark on the world with his brother in arms at his side and with the Avatar leading the charge.&nbsp;</span></p><p><b><br></b></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">But it wasn’t meant to be. The Avatar in her greatness would defeat General Kuvira long before he and his unit would arrive. Instead of fighting soldiers, he spent his first visit to Republic City helping put out fires, clear rubble and rescuing people and occasionally dealing with the newest addtion to the city, spirits. Later in life he would think back to that year as the most useful, proud and at peace he had ever been since joining the military. But hindsight is twenty twenty, in the moment the only thing he felt was burning frustration. The city smelled, its inhabitants were ungrateful and complained constantly. The only silver lining for a young Hajime-Taiyo was that the criminal syndicates where still active and that with the Police still in disarray, his unit was “encouraged” to help out with “Law and order”. Towards the end of his time in Republic City Hajime-Taiyo was invited to to join a special group of soldiers that would prevent something like this from ever happneing again.&nbsp;</span></p><h3><span style="font-size:13.999999999999998pt;font-family:Arial, sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">“Congratulations Soldier,&nbsp; you have been selected to become all that you can be….”</span></h3><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Redeployed to volcanic island someplace near the Fire Nation. Hajime-Taiyo would spend the 5 years training in urban and rural warfare and stealth and infiltration tactics. But most of all he was pushed beyond his self perceived limits to harnes the power of Combustion bending. When he started there had been 100 of them, now they where 12. The day after his 30th birthday he and his squad where given there first mission, tople a so called “bandit king” on the southern border of the Earth Federation. E.F had been reluctant to act as the Bandit King was the son, of a son of a cousin to an older earth king or something like that. At the time, that wasn’t what was important. What was important was his duty to the mission and finally putting his skills to the test. It wasn’t until they where sailing back to base that they had passed through is home village twice. His future wife would ask him sometimes what he did in the military. On good days he would say “try and make the world a better place”. But most of the time he would say “hurt people”.&nbsp;</span></p><h3><span style="font-size:13.999999999999998pt;font-family:Arial, sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">“So you are a soldier?” “I was.”</span><span style="border:none;width:211px;height:211px;"><img src="https://lh7-us.googleusercontent.com/PMhQUxDoXbrc47aPQ2DU7qV60FTpdcquewHet8GJQcaO157R2ghslFyDsq-zeUOPuVy9UqgkTVlnNR2Lxde-P6g7WKcfeY2NM836eodmgcUsRzm-sXTUcw1rEnY5zCl9eWjcDntWnFNoR3yq3bMvDUo" width="211" height="211" style="margin-left:0px;" alt="PMhQUxDoXbrc47aPQ2DU7qV60FTpdcquewHet8GJQcaO157R2ghslFyDsq-zeUOPuVy9UqgkTVlnNR2Lxde-P6g7WKcfeY2NM836eodmgcUsRzm-sXTUcw1rEnY5zCl9eWjcDntWnFNoR3yq3bMvDUo"></span></h3><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Fifteen years later Hajime-Taiyo would find himself in Republic city again for the 4th or 5th time that year, but this time not for a mission. He was trying not to stare at the bartender. Her name is Toki Mibu, and she sometimes sings and plays in something called a “rock” band. She walks with a bit of a limp,having lost half her right leg during the Kuvira uprising. Large artistic tattoos mix with the scaring and burn marks on the right side of her body. She is a blanket thief, spends hours styling her short Mowhawk, sings in her sleep and despite her aggressive and direct demenor a wonderful listener and the love is his life.&nbsp;</span></p><p><b><br></b></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Tonight is her last night in the Bar and in Republic City. Tonight they got married in her bar. Tomorrow they are leaving the city to return to Hajime-Taiyo’s village. The two have never had a conventional relationship, a decade ago a one night stand, turned into a morning chat about scars. Over the year he would stop by and sometimes she was seeing someone and they would just talk. Othertimes she wasn’t and they would talk… in the morning. One of those mornings she told him that They where ‘together and exclusive’ and he found that he liked that idea, that they would face the future together.&nbsp;</span><span style="border:none;width:167px;height:167px;"><img src="https://lh7-us.googleusercontent.com/_ygKIf9M_k-Qfug1s4aL22XySlZDWGeWrZNKa2o2hVirNdD2dhO1GIRJ-LzRWwsQTlnU8-zRYBCGfYv8IEMLZKvgrjZdGDhfdYBhs2LCJk446ksK2kfZFt593jlBPlvNXmwC-3UrhpSRRlRA63aeP9w" width="167" height="167" style="margin-left:0px;" alt="_ygKIf9M_k-Qfug1s4aL22XySlZDWGeWrZNKa2o2hVirNdD2dhO1GIRJ-LzRWwsQTlnU8-zRYBCGfYv8IEMLZKvgrjZdGDhfdYBhs2LCJk446ksK2kfZFt593jlBPlvNXmwC-3UrhpSRRlRA63aeP9w"></span></p><p><b><br></b></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">As the last of the patrons finally shuffled out drunkin well wishes and blessing and she locked the door and than yelled at their baby “I need you to come out, you are killing my feet!”. 10 months ago they had decided to have a baby. They weren’t sure if they would be the greatest parents, but if they didn’t try they would live in regret. He would leave the army and she would sell her families bar and they would run off to the country side and try and live a new life together.&nbsp;</span></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">“‘Foot’, love. You only have one foot.”</span></p><p></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">He dodge the rock thrown at his face, but only just.</span></p><div><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;"><br></span></div>'

**Comment by LeeDurant** [comment] 2023-12-21 01:17
`<p dir="ltr"><span style="font-size:26pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Hajime-Taiyo Chiu-Wei, The Elder</span></p><p dir="ltr"><span style="font-size:15pt;font-family:Arial, sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">I don’t want to hurt people anymore</span></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Age: 45</span></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Careers: Ex-Military, “Old dad” just trying to get it together</span></p><p><b><br></b></p><h3><span style="font-size:13.999999999999998pt;font-family:Arial, sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">“See the world, go to exotic places, Join the Army, and travel around the world for nothing.”&nbsp;</span></h3><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Hajime-Taiyo wasn’t sure what he wanted to do with his life being secondborn meant his life wasn’t as pre-determined as his older brother's. But raising a village out of the earth and the labor associated with it wasn’t how he planned to make his mark on the world. Village be damned, he would make his way with or without his family. Oh to be young and dumb again.&nbsp;</span></p><h3><span style="font-size:13.999999999999998pt;font-family:Arial, sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">“Never forget”</span></h3><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">While in basic training, Republic City was attacked by the “Great unifier” General Kuvira. He will always remember the furver he felt in that moment. Months of&nbsp; aptitude testing, drilling, medical evaluations, combat exercises, medical and psychological testing. Learning the ins and outs of other martial arts and bending forms as well as the histories of the other nations. All while learning about machines that wouldn’t be common place in the village he grew up in for years.</span><span style="border:none;width:210px;height:210px;"><img src="https://lh7-us.googleusercontent.com/RoYJRL5r7CX3Xj1DlHM5Dyc74_5elcFeHaO5gx_OmVQTlaRmfPjVrUCJyfCeo0ZmGl6jbY99dT20EhSrUgEPn8c5WhuWq4iE7QxXzRaMYby8ZObIOxr6J8jb8M9mioOEhMYJj8sc9aHsQV4J8mowMjY" width="210" height="210" style="margin-left:0px;" alt="RoYJRL5r7CX3Xj1DlHM5Dyc74_5elcFeHaO5gx_OmVQTlaRmfPjVrUCJyfCeo0ZmGl6jbY99dT20EhSrUgEPn8c5WhuWq4iE7QxXzRaMYby8ZObIOxr6J8jb8M9mioOEhMYJj8sc9aHsQV4J8mowMjY"></span></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">And at last he would be able to put all these things to work and not just on bandits or some provincial Warlord. But real soliders trained for war. He would make his mark on the world with his brother in arms at his side and with the Avatar leading the charge.&nbsp;</span></p><p><b><br></b></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">But it wasn’t meant to be. The Avatar in her greatness would defeat General Kuvira long before he and his unit would arrive. Instead of fighting soldiers, he spent his first visit to Republic City helping put out fires, clear rubble and rescuing people and occasionally dealing with the newest addtion to the city, spirits. Later in life he would think back to that year as the most useful, proud and at peace he had ever been since joining the military. But hindsight is twenty twenty, in the moment the only thing he felt was burning frustration. The city smelled, its inhabitants were ungrateful and complained constantly. The only silver lining for a young Hajime-Taiyo was that the criminal syndicates where still active and that with the Police still in disarray, his unit was “encouraged” to help out with “Law and order”. Towards the end of his time in Republic City Hajime-Taiyo was invited to to join a special group of soldiers that would prevent something like this from ever happneing again.&nbsp;</span></p><h3><span style="font-size:13.999999999999998pt;font-family:Arial, sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">“Congratulations Soldier,&nbsp; you have been selected to become all that you can be….”</span></h3><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Redeployed to volcanic island someplace near the Fire Nation. Hajime-Taiyo would spend the 5 years training in urban and rural warfare and stealth and infiltration tactics. But most of all he was pushed beyond his self perceived limits to harnes the power of Combustion bending. When he started there had been 100 of them, now they where 12. The day after his 30th birthday he and his squad where given there first mission, tople a so called “bandit king” on the southern border of the Earth Federation. E.F had been reluctant to act as the Bandit King was the son, of a son of a cousin to an older earth king or something like that. At the time, that wasn’t what was important. What was important was his duty to the mission and finally putting his skills to the test. It wasn’t until they where sailing back to base that they had passed through is home village twice. His future wife would ask him sometimes what he did in the military. On good days he would say “try and make the world a better place”. But most of the time he would say “hurt people”.&nbsp;</span></p><h3><span style="font-size:13.999999999999998pt;font-family:Arial, sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">“So you are a soldier?” “I was.”</span><span style="border:none;width:211px;height:211px;"><img src="https://lh7-us.googleusercontent.com/PMhQUxDoXbrc47aPQ2DU7qV60FTpdcquewHet8GJQcaO157R2ghslFyDsq-zeUOPuVy9UqgkTVlnNR2Lxde-P6g7WKcfeY2NM836eodmgcUsRzm-sXTUcw1rEnY5zCl9eWjcDntWnFNoR3yq3bMvDUo" width="211" height="211" style="margin-left:0px;" alt="PMhQUxDoXbrc47aPQ2DU7qV60FTpdcquewHet8GJQcaO157R2ghslFyDsq-zeUOPuVy9UqgkTVlnNR2Lxde-P6g7WKcfeY2NM836eodmgcUsRzm-sXTUcw1rEnY5zCl9eWjcDntWnFNoR3yq3bMvDUo"></span></h3><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Fifteen years later Hajime-Taiyo would find himself in Republic city again for the 4th or 5th time that year, but this time not for a mission. He was trying not to stare at the bartender. Her name is Toki Mibu, and she sometimes sings and plays in something called a “rock” band. She walks with a bit of a limp,having lost half her right leg during the Kuvira uprising. Large artistic tattoos mix with the scaring and burn marks on the right side of her body. She is a blanket thief, spends hours styling her short Mowhawk, sings in her sleep and despite her aggressive and direct demenor a wonderful listener and the love is his life.&nbsp;</span></p><p><b><br></b></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">Tonight is her last night in the Bar and in Republic City. Tonight they got married in her bar. Tomorrow they are leaving the city to return to Hajime-Taiyo’s village. The two have never had a conventional relationship, a decade ago a one night stand, turned into a morning chat about scars. Over the year he would stop by and sometimes she was seeing someone and they would just talk. Othertimes she wasn’t and they would talk… in the morning. One of those mornings she told him that They where ‘together and exclusive’ and he found that he liked that idea, that they would face the future together.&nbsp;</span><span style="border:none;width:167px;height:167px;"><img src="https://lh7-us.googleusercontent.com/_ygKIf9M_k-Qfug1s4aL22XySlZDWGeWrZNKa2o2hVirNdD2dhO1GIRJ-LzRWwsQTlnU8-zRYBCGfYv8IEMLZKvgrjZdGDhfdYBhs2LCJk446ksK2kfZFt593jlBPlvNXmwC-3UrhpSRRlRA63aeP9w" width="167" height="167" style="margin-left:0px;" alt="_ygKIf9M_k-Qfug1s4aL22XySlZDWGeWrZNKa2o2hVirNdD2dhO1GIRJ-LzRWwsQTlnU8-zRYBCGfYv8IEMLZKvgrjZdGDhfdYBhs2LCJk446ksK2kfZFt593jlBPlvNXmwC-3UrhpSRRlRA63aeP9w"></span></p><p><b><br></b></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">As the last of the patrons finally shuffled out drunkin well wishes and blessing and she locked the door and than yelled at their baby “I need you to come out, you are killing my feet!”. 10 months ago they had decided to have a baby. They weren’t sure if they would be the greatest parents, but if they didn’t try they would live in regret. He would leave the army and she would sell her families bar and they would run off to the country side and try and live a new life together.&nbsp;</span></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">“‘Foot’, love. You only have one foot.”</span></p><p></p><p dir="ltr"><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;">He dodge the rock thrown at his face, but only just.</span></p><div><span style="font-size:11pt;font-family:Arial, sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;text-decoration:none;"><br></span></div>`

**Comment by LeeDurant** [comment] 2023-12-21 01:19
Thank you for being so considered in trying to figure this out! Its a real brain teaser since I don't see the pattern myself.

**Comment by eXaminator** [comment] 2023-12-21 11:02
Ok, this is strange. I still cannot replicate the issue. :( So I will further need your help to debug this, sorry for that.

Ok, here are some more things you could try to help further narrow this down:

1. What Foundry VTT Version are you on? Make sure you're on the latest V11 release.
2. Could you maybe remove the entry text for that entity and try to import it again? I want to narrow the problem down to the entry Text. You could make a copy of the entity first. If it works after clearing the entry text, you could try to partially reintroduce parts of that entry and try reimporting and see if / when it starts breaking. Maybe you could narrow it down to the specific part of the entry that breaks this, even though it would be a bit of work. But at this point I'm also a bit lost to what breaks it.

**Comment by eXaminator** [comment] 2024-03-29 16:44
@LeeDurant Do you still have this issue? If yes, could you reply to my earlier message?

**Comment by LeeDurant** [comment] 2024-03-29 16:48
Hi there, unfortunately I'm no longer using the module as my game with it ended prematurely.

**Comment by eXaminator** [comment] 2024-03-29 16:57
Ok, no worries. In that case I'll close the issue.

**Closed by eXaminator** 2024-03-29 16:57 UTC
